Repository Mysterken/DLsiteMetadata, pull requests merged in 2025-02, with the labels that each got.

#8 feature: Support RE work id + no selection if game name is work id or link
  source/DLsiteMetadataProvider.cs
  source/DLsiteScrapper.cs
Labels: enhancement

#9 V1.12
  manifests/InstallerManifest.yaml
  source/DLsiteMetadata.csproj
  source/DLsiteMetadataProvider.cs
  source/DLsiteScrapper.cs
  source/extension.yaml
  source/packages.config
Labels: enhancement

#10 feature: update AddonId and README icon
  documentation/icon.png
  manifests/InstallerManifest.yaml
  source/extension.yaml
Labels: documentation

#12 V1.13
  README.md
  manifests/InstallerManifest.yaml
  manifests/manifest.yaml
  source/DLsiteMetadataProvider.cs
  source/DLsiteMetadataSettings.cs
  source/DLsiteMetadataSettingsView.xaml
  source/DLsiteScrapper.cs
  source/DLsiteScrapperResult.cs
  source/SupportedLanguages.cs
  source/extension.yaml
Labels: bug, enhancement

#13 V1.13.1
  manifests/InstallerManifest.yaml
  source/DLsiteMetadataPlugin.cs
  source/extension.yaml
Labels: bug
